### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 3566: invalid continuation byte

### ISSUE THREAD

**Issue by ReneMuetti** [jkolezyn/cert_tree#3]
[/share/homes/admin] # python
Python 3.10.4 (main, Apr 13 2022, 08:47:51) [GCC 8.4.0] on linux

[/share/homes/admin] # python cert_tree.py  -p /share/CACHEDEV1_DATA/.qpkg/container-station/etc/ssl/certs/ca-certificates.crt
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/homes/admin/cert_tree.py", line 210, in <module>
    main()
  File "/share/CACHEDEV1_DATA/homes/admin/cert_tree.py", line 203, in main
    certs = create_certs(certs)
  File "/share/CACHEDEV1_DATA/homes/admin/cert_tree.py", line 62, in create_certs
    certs.append(create_cert(content, position))
  File "/share/CACHEDEV1_DATA/homes/admin/cert_tree.py", line 73, in create_cert
    for line in out.decode().split('\n'):
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 3566: invalid continuation byte

Running on QNAP NAS with OS 5.x

**Comment by carlitros900** [comment]
I have found this error with some certificate that has a name with a latin encoding.
Change line 76 by
    for line in out.decode(errors='ignore').split('\n'):
worked for me.

**Comment by jkolezyn** [comment]
Thanks, but that just ignores the error. Could you perhaps produce an example of cert which causes the error?

**Comment by carlitros900** [comment]
Hi, thanks. Found the error in cert downloable from https://www.seg-social.es/wps/wcm/connect/wss/dfde8c9e-6de7-48a0-bb60-b7f570ec3ae5/ACGISSv2.cer?MOD=AJPERES
